service: wsapi

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    CONNECTIONS_TABLE: !Ref ConnectionsTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamo:PutItem
            - dynamo:DeleteItem
            - dynamo:Scan
            - dynamo:Query
          Resource: 
            - !GetAtt ConnectionsTable.Arn

package:
  individually: true

build: 
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

functions:
  wsConnection:
    handler: src/functions/wsConnection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: sendMessage
  healthCheck:
    handler: src/functions/healthCheck.handler
    events:
      - httpApi:
          method: GET
          path: /healthcheck


resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ConnectionsTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: connectionId
              AttributeType: S
          KeySchema:
            - AttributeName: connectionId
              KeyType: HASH