service: wsapi

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  websocketsApiRouteSelectionExpression: $request.body.action

package:
  individually: true

build: 
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

functions:
  wsConnection:
    handler: src/functions/wsConnection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  healthCheck:
    handler: src/functions/healthCheck.handler
    events:
      - httpApi:
          method: GET
          path: /healthcheck
